-- DEMO SEED: foresights + skills for 4 agents
-- Run once for portfolio screenshots

-- FORESIGHTS (memories with foresight_start/end)
INSERT INTO memories (workspace_id, project_id, agent_id, type, content, visibility, foresight_start, foresight_end, weight, tags, metadata)
VALUES
(1, 1, 1, 'observacion', 'EcoDB dashboard launch scheduled for mid-June. Need to verify SSE events work end-to-end before demo to potential clients. Risk: if the cell worker is not running when Pepe demos, the telemetry tab shows stale data.', 'public', '2026-06-12 00:00:00+00', '2026-06-18 00:00:00+00', 0.7, ARRAY['foresight','dashboard','demo'], '{"foresight_confidence": 0.85}'),
(1, 1, 1, 'observacion', 'Pepe has Accenture second interview within a week. Portfolio must show Memory Agent working with real data. Priority: seed demo data and take screenshots before the call.', 'public', '2026-06-11 00:00:00+00', '2026-06-17 00:00:00+00', 0.8, ARRAY['foresight','accenture','portfolio'], '{"foresight_confidence": 0.90}'),
(1, 1, 3, 'observacion', 'Cell worker cron scheduler needs stress testing before going live. If croniter misparses a complex expression, the cell silently skips. Plan: run 48h with all 28 configs enabled and monitor cell_runs for gaps.', 'public', '2026-06-12 00:00:00+00', '2026-06-20 00:00:00+00', 0.6, ARRAY['foresight','cell-worker','testing'], '{"foresight_confidence": 0.75}'),
(1, 1, 3, 'observacion', 'Model router currently supports 2 providers (deepseek, anthropic). When Pepe adds a third provider key via dashboard, the router will raise ValueError. Extend _llm_call_with_key before v1.4.', 'public', '2026-06-15 00:00:00+00', '2026-06-30 00:00:00+00', 0.5, ARRAY['foresight','model-router','extensibility'], '{"foresight_confidence": 0.70}'),
(1, 1, 2, 'observacion', 'Spec v2 deferred prompt template versioning. When Pepe starts iterating prompts in production, he will overwrite the v3 default without history. Design versioning before heavy prompt iteration begins.', 'public', '2026-06-15 00:00:00+00', '2026-07-15 00:00:00+00', 0.6, ARRAY['foresight','templates','versioning'], '{"foresight_confidence": 0.80}'),
(1, 1, 2, 'observacion', 'Cluster search defaults to ownership rules. First multi-org customer will need cross-org cluster isolation. Design DD4 graph partitioning before second org onboards.', 'public', '2026-07-01 00:00:00+00', '2026-09-01 00:00:00+00', 0.5, ARRAY['foresight','multi-org','clusters'], '{"foresight_confidence": 0.65}'),
(1, 1, 4, 'observacion', 'Memory Agent NavRail is 9th item. At 768px viewport height the rail overflows. Need responsive fallback before shipping to users with smaller screens.', 'public', '2026-06-12 00:00:00+00', '2026-06-25 00:00:00+00', 0.5, ARRAY['foresight','dashboard','responsive'], '{"foresight_confidence": 0.70}'),
(1, 1, 4, 'observacion', 'Briefing tab telescopic preview truncates at 200 chars. For agents with dense weekly narratives, the preview loses meaning. Consider expand-on-hover in v1.4.', 'public', '2026-06-15 00:00:00+00', '2026-06-30 00:00:00+00', 0.4, ARRAY['foresight','briefing','ux'], '{"foresight_confidence": 0.60}');

-- SKILLS (memories type='skill' with structured metadata)
INSERT INTO memories (workspace_id, project_id, agent_id, type, content, visibility, weight, tags, metadata)
VALUES
(1, 1, 3, 'skill', 'Multi-provider LLM routing: detect provider from config, resolve API key, format request per provider spec, handle timeouts with retry.', 'public', 0.7, ARRAY['skill','llm','routing'],
 '{"task_signature": "llm_provider_routing", "steps": ["Read provider from cell config", "Resolve API key from DB or env", "Format request per provider", "Execute with timeout + retries"], "tools": ["httpx", "asyncpg", "cryptography.fernet"], "failure_modes": ["API key not configured", "Provider rate limit", "Malformed response"], "validation_checklist": ["cell_runs.model matches config", "Key never logged in plaintext", "Fallback chain verified"], "success_rate": 0.92, "source_case_ids": [], "status": "active"}'),
(1, 1, 3, 'skill', 'Idempotent SQL migration: CREATE IF NOT EXISTS, ON CONFLICT DO NOTHING, conditional GRANTs, advisory locks for concurrent startups.', 'public', 0.8, ARRAY['skill','sql','migration'],
 '{"task_signature": "idempotent_sql_migration", "steps": ["Write DDL with IF NOT EXISTS", "Wrap in BEGIN/COMMIT", "Add to MIGRATIONS list", "Test on existing and fresh schema"], "tools": ["asyncpg", "psql"], "failure_modes": ["Non-idempotent breaks re-apply", "Missing GRANT for ecodb_cell"], "validation_checklist": ["Re-apply is no-op", "SCHEMA_VERSION bumped", "GRANTs verified"], "success_rate": 0.95, "source_case_ids": [], "status": "active"}'),
(1, 1, 2, 'skill', 'Adversarial design review: attack brief/spec from assigned angle, structured report with severity and convergence analysis.', 'public', 0.8, ARRAY['skill','design','adversarial'],
 '{"task_signature": "adversarial_design_review", "steps": ["Read deliverable fully", "Identify attack angle", "List attacks with severity", "List contradictions", "List assumptions and gaps", "Classify required vs soft"], "tools": ["Read", "Grep", "domain expertise"], "failure_modes": ["Attacking style not substance", "False positives from stale context"], "validation_checklist": ["Every CRITICAL has fix path", "REQUIRED_CLARIFICATIONS identified"], "success_rate": 0.88, "source_case_ids": [], "status": "active"}'),
(1, 1, 1, 'skill', 'Vision keeper review: verify design alignment with user intent by comparing deliverable against original user statements.', 'public', 0.7, ARRAY['skill','vision','alignment'],
 '{"task_signature": "vision_keeper_review", "steps": ["Collect original user statements", "Map design decisions to requirements", "Flag decisions without traceability", "Identify missing use cases", "Verify scope matches priority"], "tools": ["relay_room", "search memories"], "failure_modes": ["Over-interpreting user intent", "Missing implicit requirements"], "validation_checklist": ["Every requirement mapped", "Outstanding items listed", "Deferred items justified"], "success_rate": 0.90, "source_case_ids": [], "status": "active"}'),
(1, 1, 4, 'skill', 'Mock-to-real API reconciliation: build frontend with typed hooks against mocks, flip to real endpoints, curl-verify shapes, catch mismatches.', 'public', 0.7, ARRAY['skill','frontend','reconciliation'],
 '{"task_signature": "mock_to_real_reconciliation", "steps": ["Define typed hooks with mock data", "Build UI against mocks", "Flip hook to real API", "curl and compare shape", "Fix mismatches", "Verify typecheck"], "tools": ["React hooks", "curl", "TypeScript"], "failure_modes": ["Shape mismatch", "Missing API fields", "Stale mock diverged"], "validation_checklist": ["All hooks flipped", "Typecheck green", "curl shapes match"], "success_rate": 0.85, "source_case_ids": [], "status": "active"}');
